// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAsD9nyHAUEU7C8xtaPyxxZyCKm1fAV5A',
    appId: '1:791401909877:web:3a823ac2865cb07a91723c',
    messagingSenderId: '791401909877',
    projectId: 'testapp-11c7e',
    authDomain: 'testapp-11c7e.firebaseapp.com',
    storageBucket: 'testapp-11c7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8kf8FliC5GjS3OQDV8ccykR4dBJiah0Y',
    appId: '1:791401909877:android:8630c3467b39d2dd91723c',
    messagingSenderId: '791401909877',
    projectId: 'testapp-11c7e',
    storageBucket: 'testapp-11c7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH396tisagHoskG9h8zkNOGq4iguj-elk',
    appId: '1:791401909877:ios:1b2d5a40defcb67491723c',
    messagingSenderId: '791401909877',
    projectId: 'testapp-11c7e',
    storageBucket: 'testapp-11c7e.appspot.com',
    iosClientId: '791401909877-jh0ehgpvvflgej1ouvtb7jmvnohjdq69.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
